### PR TITLE
Update wireutils

### PR DESCRIPTION
**Pull request by yrsegal**
just some standardization of wireutils across the myriad places it's used :P

### CODE REVIEW

**Comment by miestasmia** [comment]
I'll check it out tonight and merge/comment :)

**Comment by yrsegal** [comment]
did you? :P

**Comment by miestasmia** [comment]
Sorry, life came in the way. I'll try to do it tomorrow :)

**Comment by yrsegal** [comment]
luckily i got THAT one in before you pulled

**Comment by miestasmia** [comment]
`checkdependencies.py` seems to hang after warning that you're not root.

**Comment by yrsegal** [comment]
huh. lemme check on that.

**Comment by yrsegal** [comment]
fixed

**Comment by miestasmia** [comment]
Looks great, merging! Thanks :smile:

**Pull request merged**
