### PR TITLE
Minor aesthetic updates

### PR DESCRIPTION
**Pull request by yrsegal**

### CODE REVIEW

**Comment by yrsegal** [comment]
oh wait new commits get added into the PR automagically? yesssss

**Comment by miestasmia** [comment]
Looks, great. Why did you import the python3 print function in checkdependencies.py, however? I prefer to use python2 whenever possible.

**Comment by yrsegal** [comment]
because I prefer `print()` ¯\_(ツ)_/¯

you can just replace it with `print` and remove that line if you want

**Comment by yrsegal** [comment]
py2 print is a go, I guess

**Comment by miestasmia** [comment]
Awesome, thanks a lot. Merging.

**Pull request merged**
